In [2]:
import numpy as np

In [3]:
a=np.array([23,44,66])

In [4]:
a

array([23, 44, 66])

In [6]:
w1,w2,w3=0.1,0.3,0.2

In [7]:
w=np.array([w1,w2,w3])

In [8]:
w

array([0.1, 0.3, 0.2])

In [9]:
w[1]

np.float64(0.3)

In [12]:
np.dot(a,w)

np.float64(28.7)

In [13]:
a*w

array([ 2.3, 13.2, 13.2])

In [14]:
a*w.sum()

array([13.8, 26.4, 39.6])

In [15]:
arr1=list(range(100000))
arr2=list(range(100000,200000))

arr1_np=np.array(arr1)
arr2_np=np.array(arr2)

In [16]:
%%time
result=0
for x,y in zip(arr1,arr2):
    result +=x*y
result

CPU times: total: 15.6 ms
Wall time: 18.1 ms


833323333350000

In [17]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: total: 15.6 ms
Wall time: 9.71 ms


np.int64(833323333350000)

In [18]:
type(arr1_np)

numpy.ndarray

In [20]:
climate=np.array([[34,56,78],
                 [45,67,33],
                 [34,22,11]])

In [23]:
#dot product
np.matmul(climate,w)

array([35.8, 31.2, 12.2])

In [24]:
climate @ w

array([35.8, 31.2, 12.2])

In [25]:
climate.shape

(3, 3)

In [27]:
climate[1:,0:1]

array([[45],
       [34]])

In [28]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.random.rand(5)

array([0.14055077, 0.48388218, 0.27819856, 0.35997792, 0.68057645])

In [39]:
np.random.randn(5,2)

array([[ 0.71647292,  1.67145061],
       [ 1.25041364, -2.37194617],
       [-0.0142573 , -0.2420741 ],
       [ 0.84492147, -0.22824539],
       [-1.4679888 , -1.2813349 ]])

In [37]:
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [40]:
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [41]:
np.arange(10,90,3).shape

(27,)

In [42]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [43]:
import os
os.getcwd()

'C:\\Users\\Vinay kumar\\Desktop\\Data Analysis & Visualisation'

In [44]:
os.listdir('.')

['.ipynb_checkpoints', 'Numpy.ipynb']

In [49]:
'Users' in os.listdir('.')

False

In [75]:
os.makedirs('./data',exist_ok=True)

In [76]:
url1='https://storage.googleapis.com/kagglesdsdata/datasets/74581/169310/loan_data_set.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260111%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260111T133109Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=2481a95b69838401027eb02efed60659aa501d04ce795213fd8ffc5f49827470810aa49199fc5bacac04653e0c699b0b6455981555fc6d48183d10435e5b0fabfe34ef8f582d3e18dce824c9743bcceae11682f730229c38d45427eed977ebdbe3911446bee81ad42f51a794b09c60778e60a792d4d6369ee4c83e820fb068881cc15c802306efe925b921c444bb3e73f337b8c6b2e1760020aeb4130b6100073c02af5e3a0cbd323ce1f8ad9ca0c9483a35329749b9ac13af3083ef1ab1f3dc8080056b94baefa0d6cb46d0d4c768ec26e9ccc99d38c3b784117309e3abe58db7c6d677ced63ce4b3ecb561da8ba2cbcd1b8ee89de9045b8181df45c7c8dc6d'
url2='https://storage.googleapis.com/kagglesdsdata/datasets/74581/169310/loan_data_set.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260111%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260111T133109Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=2481a95b69838401027eb02efed60659aa501d04ce795213fd8ffc5f49827470810aa49199fc5bacac04653e0c699b0b6455981555fc6d48183d10435e5b0fabfe34ef8f582d3e18dce824c9743bcceae11682f730229c38d45427eed977ebdbe3911446bee81ad42f51a794b09c60778e60a792d4d6369ee4c83e820fb068881cc15c802306efe925b921c444bb3e73f337b8c6b2e1760020aeb4130b6100073c02af5e3a0cbd323ce1f8ad9ca0c9483a35329749b9ac13af3083ef1ab1f3dc8080056b94baefa0d6cb46d0d4c768ec26e9ccc99d38c3b784117309e3abe58db7c6d677ced63ce4b3ecb561da8ba2cbcd1b8ee89de9045b8181df45c7c8dc6d'

In [77]:
import urllib.request

In [78]:
urllib.request.urlretrieve(url1,'./data/loans1.txt')
urllib.request.urlretrieve(url2,'./data/loans2.txt')

('./data/loans2.txt', <http.client.HTTPMessage at 0x20841978710>)

In [79]:
os.listdir('./data')
        

['loans1.txt', 'loans2.txt']

In [80]:
f1=open('./data/loans1.txt',mode='r')
f2=open('./data/loans2.txt',mode='r')

In [81]:
f1_content=f1.read()
print(f1_content)

Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
LP001002,Male,No,0,Graduate,No,5849,0,,360,1,Urban,Y
LP001003,Male,Yes,1,Graduate,No,4583,1508,128,360,1,Rural,N
LP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
LP001008,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y
LP001011,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y
LP001013,Male,Yes,0,Not Graduate,No,2333,1516,95,360,1,Urban,Y
LP001014,Male,Yes,3+,Graduate,No,3036,2504,158,360,0,Semiurban,N
LP001018,Male,Yes,2,Graduate,No,4006,1526,168,360,1,Urban,Y
LP001020,Male,Yes,1,Graduate,No,12841,10968,349,360,1,Semiurban,N
LP001024,Male,Yes,2,Graduate,No,3200,700,70,360,1,Urban,Y
LP001027,Male,Yes,2,Graduate,,2500,1840,109,360,1,Urban,Y
LP001028,Male,Yes,2,Graduate,No,3073,8106,200,360,1,Urban,Y
LP001029,Male,No,0,Graduate,No,1853,2840,114,360,1,Rural,N

In [82]:
f1.close()
f2.close()

In [85]:
with open('./data/loans1.txt','r') as f1:
          file_lines=f1.readlines()

In [87]:
file_lines[0].strip()

'Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status'

In [88]:
'LP001002,Male,No,0,Graduate,No,5849,0,,360,1,Urban,Y'.split(',')

['LP001002',
 'Male',
 'No',
 '0',
 'Graduate',
 'No',
 '5849',
 '0',
 '',
 '360',
 '1',
 'Urban',
 'Y']

In [96]:
def parse_headers(header_line):
    return header_line.strip().split(',')

In [117]:
headers=parse_headers(file_lines[0])

In [118]:
headers

['Loan_ID',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status']

In [119]:
def parse_value(data_line):
    values=[]
    for item in data_line.strip().split(','):
        values.append(item)
    return values

In [120]:
def create_item_dict(values,headers):
    r=[]
    for value,header in zip(value,headers):
        r[header]=value
    return r

In [124]:
file_lines[4]

'LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y\n'

In [125]:
def read_csv(path):
    r=[]
    with open(path,'r') as f:
        lines=f.readlines()
        headers=parse_headers(lines[0])
        for data_line in lines[1:]:
            values=parse_value(data_line)
            item_dict=create_item_dict(values,headers)
            r.append(item_dict)
    return r

In [126]:
with open('./data/loans1.txt','r') as f1:
          print(f1.read())

Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
LP001002,Male,No,0,Graduate,No,5849,0,,360,1,Urban,Y
LP001003,Male,Yes,1,Graduate,No,4583,1508,128,360,1,Rural,N
LP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
LP001008,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y
LP001011,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y
LP001013,Male,Yes,0,Not Graduate,No,2333,1516,95,360,1,Urban,Y
LP001014,Male,Yes,3+,Graduate,No,3036,2504,158,360,0,Semiurban,N
LP001018,Male,Yes,2,Graduate,No,4006,1526,168,360,1,Urban,Y
LP001020,Male,Yes,1,Graduate,No,12841,10968,349,360,1,Semiurban,N
LP001024,Male,Yes,2,Graduate,No,3200,700,70,360,1,Urban,Y
LP001027,Male,Yes,2,Graduate,,2500,1840,109,360,1,Urban,Y
LP001028,Male,Yes,2,Graduate,No,3073,8106,200,360,1,Urban,Y
LP001029,Male,No,0,Graduate,No,1853,2840,114,360,1,Rural,N

In [127]:
read_csv('./data/loans1.txt')

UnboundLocalError: cannot access local variable 'value' where it is not associated with a value